### ISSUE TITLE
--no-playlist support

### ISSUE THREAD

**Issue by joeriakkerman** [creotiv/deezer_playlist_mp3_downloader#4]
When the program encounters a youtube playlist it tries to download the full playlist

> Parsing: Glowinthedark - Wat Doe Jij
 Url: /watch?v=uydGbsh_5iI&amp;list=PLrjBPVLRnnIxCyZmHeyAdZ7jQ5wdOG90w
[youtube:playlist] Downloading playlist PLrjBPVLRnnIxCyZmHeyAdZ7jQ5wdOG90w - add --no-playlist to just download video uydGbsh_5iI
[youtube:playlist] PLrjBPVLRnnIxCyZmHeyAdZ7jQ5wdOG90w: Downloading webpage
[download] Downloading playlist: Wat Doe Jij – GLOWINTHEDARK
[youtube:playlist] playlist Wat Doe Jij – GLOWINTHEDARK: Downloading 34 videos
[download] Downloading video 1 of 34
[youtube] uydGbsh_5iI: Downloading webpage
[youtube] uydGbsh_5iI: Downloading video info webpage
[youtube] uydGbsh_5iI: Extracting video information
WARNING: unable to extract uploader nickname

But it gives me this error:

> youtube_dl.utils.DownloadError: ERROR: yzFVrgUAwJo: YouTube said: "SFB x GLOWINTHEDARK - Ander..."
The YouTube account associated with this video has been terminated due to multiple third-party notifications of copyright infringement.

So it is not able to download the file and then it stops downloading for all the other files as well.
Maybe there could be a fix, when one file is not downloadable it skips that particular file and goes on with the next one.
Also the --no-playlist command is not working with the current program, it only supports --playlist, or am I using it wrongly? : 

>dzget -f mp3 -d "[MY_DIR]" --no-playlist "[MY_PLAYLIST_FROM_DEEZER]"
usage: dzget [-h] [-p] [-f format] [-d directory] [-q quality] url
dzget: error: unrecognized arguments: --no-playlist

I do wanna say that your programm works very smoothly and I like it a lot!

**Comment by creotiv** [comment]
Got it. Will try to fix ASAP

**Comment by joeriakkerman** [comment]
You're the man!

**Comment by creotiv** [comment]
fixed
